version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
      - "5173:5173"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server/user-data:/app/user-data
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend-dev:
    build:
      context: ./interface
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./interface:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev

volumes:
  redis_data:
